### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Coloris** [fubar2/pcapGrok#3]
> ast@:~/pcapGrok# python3 pcapGrok.py 
> Traceback (most recent call last):
>   File "pcapGrok.py", line 489, in <module>
>     infiles = [x for x in args.pcaps if os.path.isfile(x)]  
> TypeError: 'NoneType' object is not iterable

Running python3 core.py does not return anything

**Comment by fubar2** [comment]
Core.py is not supposed to do anything if run by itself - it's just a class container. The error message suggests you did not provide an input -i pcap file. Please try providing one to pcapGrok.py - as the help describes you need at least a pcap input file and an output picture name 

> 
> usage: pcapGrok.py [-h] [-a] [-b [BLACKLIST [BLACKLIST ...]]]
>                    [-E LAYOUTENGINE] [-fi] [-fo] [-g GRAPHVIZ] [-G GEOPATH]
>                    [-hf HOSTSFILE] [-i [PCAPS [PCAPS ...]]] [-k KYDDBPATH]
>                    [-l GEOLANG] [--layer2] [--layer3] [--layer4] [-n NMAX]
>                    [-o OUTPATH] [-p PICTURES] [-P] [-S]
>                    [-r [RESTRICT [RESTRICT ...]]] [-s SHAPE] [-T]
>                    [-w [WHITELIST [WHITELIST ...]]] [-W]

So, assuming you have the maxminddb in the default location, a minimal command line to produce 3 layers from foo.pcap with the annotated network diagram image file suffix "mytest.pdf" would be:

> python3 pcapGrok.py -i foo.pcap -o mytest.pdf 

I hope this helps?

**Comment by Coloris** [comment]
Thank you, -o mytest.pdf creates a fodler, I had to add -p mytest.pdf instead !

**Comment by fubar2** [comment]
Yes. -o will write all the outputs including the log to a new output directory otherwise everything is written to the working directory.
To write all the outputs to [somedirectory] you might want:
-o somedirectory -p somepicture.pdf
